### ISSUE TITLE
error installing django-memcache < 1.5x

### ISSUE THREAD

**Issue by landongn** [lionheart/django-template#5]
Probably just needs a version bump in the requirements file.  seems > 1.5 fixed the problem. 

error:

```
(api)> $ pip3 install -r requirements.txt
Collecting https://github.com/jmoiron/johnny-cache/archive/37e75019625979487f17b47050da7f0af3fea42c.zip (from -r requirements.txt (line 14))
  Downloading https://github.com/jmoiron/johnny-cache/archive/37e75019625979487f17b47050da7f0af3fea42c.zip (64kB)
    100% |████████████████████████████████| 65kB 467kB/s
Collecting django==1.8 (from -r requirements.txt (line 1))
  Using cached Django-1.8-py2.py3-none-any.whl
Collecting psycopg2==2.5.3 (from -r requirements.txt (line 2))
  Using cached psycopg2-2.5.3.tar.gz
Collecting py-bcrypt==0.4 (from -r requirements.txt (line 3))
  Using cached py-bcrypt-0.4.tar.gz
Collecting python-memcached==1.48 (from -r requirements.txt (line 4))
  Using cached python-memcached-1.48.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/8b/t5vzcjk15txbf8vcwx41kc5w0000gn/T/pip-build-j_uuyzlj/python-memcached/setup.py", line 4, in <module>
        import memcache
      File "/private/var/folders/8b/t5vzcjk15txbf8vcwx41kc5w0000gn/T/pip-build-j_uuyzlj/python-memcached/memcache.py", line 393
        except socket.error, msg:
                           ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/8b/t5vzcjk15txbf8vcwx41kc5w0000gn/T/pip-build-j_uuyzlj/python-memcached
```

**Comment by dlo** [comment]
Thanks @landongn!
